- name: user-input.yml - Collect all the user prompts in one playbook. Check if prompt is needed
  hosts: localhost
  become: no


  pre_tasks:

    # Check to see what's actually needed to prompt the user for ---------------------------
    - name: Get git name, if it exists
      git_config:
        name: user.name
        scope: global
      register: git_name

    - name: Get git email, if it exists
      git_config:
        name: user.email
        scope: global
      register: git_email

    - name: Check if ssh key exists
      stat:
        path: ~/.ssh/id_rsa
      register: ssh_key

    # Git and SSH user information -------------------------------------
    - name: Get user's name
      ansible.builtin.pause:
        prompt: "Enter your full name eg. John Smith"
      register: user_name
      when: not git_name.config_value

    - name: Get user's email
      ansible.builtin.pause:
        prompt: "Enter your email eg. john.smith@email.com"
      register: email
      when: not git_email.config_value

    - name: Get SSH passphrase
      ansible.builtin.pause:
        prompt: "Enter the passphrase for the SSH key"
        echo: false
      register: ssh_passphrase
      when: not ssh_key.stat.exists

  tasks:

    # ssh key config ----------------------------------------------
    - name: generate SSH key
      user:
        name: "{{ ansible_user }}"
        generate_ssh_key: yes
        ssh_key_type: rsa
        ssh_key_bits: 4096
        ssh_key_file: .ssh/id_rsa
        ssh_key_passphrase: "{{ ssh_passphrase.user_input }}"
        force: no
      when: ssh_passphrase.user_input is defined

    # Git config -------------------------------------------------
    - name: setup git name
      git_config:
        name: user.name
        scope: global
        value: "{{ user_name.user_input }}"
      when: user_name.user_input is defined

    - name: setup git user email
      git_config:
        name: user.email
        scope: global
        value: "{{ email.user_input }}"
      when: email.user_input is defined

