# Package Installation --------------------------------------
- name: install packages
  become: true
  pacman:
    update_cache: yes
    name:
      - alacritty
      - arandr
      - bash-completion
      - btop
      - dmenu
      - flatpak
      - firefox
      - cameractrls
      - git
      - gvim
      - htop
      - keychain
      - linux-lts-headers
      - neofetch
      - neovim
      - npm
      - openssh
      - peek
      - remmina
      - rofi
      - samba
      - shutter
      - smbclient
      - the_silver_searcher
      - tig
      - tmux
      - tree
      - xbanish
      - xclip
      - yay

      # Fonts
      - ttf-dejavu
      - ttf-font-awesome
      - ttf-ubuntu-font-family

      # wms
      - i3
      - xfce4
      - xfce4-power-manager
      - xfce4-panel

      # Programming
      - base-devel
      - ccls
      - cscope
      - clang
      - ctags
      - fzf
      - go
      - python
      - python-pip
      - python-pexpect
      - python-setuptools
      - yarn
      - zed
