# ---------------------------------------------------------------------
# Call other playbooks
# ---------------------------------------------------------------------
- name: Run playbook to install all Debian packages
  ansible.builtin.include: debian.yml
  when: ansible_facts['os_family'] == "Debian"

- name: Run playbook to install all Arch packages
  ansible.builtin.include: arch.yml
  when: ansible_facts['os_family'] == "Archlinux"

# Start Services ---------------------------------------------------
- name: Get service facts
  ansible.builtin.service_facts:

- name: Start ssh service
  become: yes
  systemd:
    name: sshd
    enabled: yes
    state: started
