# Git config -------------------------------------------------
- name: setup git name
  git_config:
    name: user.name
    scope: global
    value: "{{ user_name.user_input }}"
  when: user_name.user_input is defined

- name: setup git user email
  git_config:
    name: user.email
    scope: global
    value: "{{ email.user_input }}"
  when: email.user_input is defined
