# Link all dotfiles found in ~/dotfiles --------------------------------------
- name: Find dotfiles in "~/dotfiles"
  find:
    paths: ~/dotfiles
    recurse: no
    file_type: file
    patterns: "\\..*"
    hidden: true
    use_regex: yes
    excludes: '.gitignore,.gitsubmodule'
  register: dotfiles

- name: Create symlinks of dotfiles to ~/
  ignore_errors: yes
  file:
    src: "{{ item.path }}"
    path: "~/{{ item.path | basename }}"
    state: link
  with_items: "{{ dotfiles.files }}"

# Link .vim/ folder from ~/dotfiles --------------------------------------
- name: Find "~/dotfiles/.vim" directory
  stat:
    path: ~/dotfiles/.vim
  register: vim

- name: Create symlink to ~/
  ignore_errors: yes
  file:
    src: "~/dotfiles/.vim"
    path: "~/.vim"
    state: link
  when: vim.stat.exists

# Link all .config/ files found in ~/dotfiles --------------------------------------
- name: Find dotfiles in "~/dotfiles/.config"
  ignore_errors: yes
  find:
    paths: ~/dotfiles/.config
    recurse: yes
    file_type: directory
    hidden: true
    use_regex: yes
    excludes: '.gitignore'
  register: configs

- name: Create symlinks to ~/.config
  ignore_errors: yes
  file:
    src: "{{ item.path }}"
    path: "~/.config/{{ item.path | basename }}"
    state: link
  with_items: "{{ configs.files }}"
